name: CI Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      # Match all branches, also the ones with slashes
      # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestbranchestags
      - '**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker with Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true  # alias docker build = docker buildx
          # Export docker image as soon as it's built. Read: https://stackoverflow.com/a/64560710
          driver: docker

      - name: Run checks
        run: cd backend && bash ci.sh
